export enum blogActionTypes {
  FETCH_BLOGS_REQUEST = 'FETCH_BLOGS_REQUEST',
  FETCH_BLOGS_SUCCESS = 'FETCH_BLOGS_SUCCESS',
  FETCH_BLOGS_FAILURE = 'FETCH_BLOGS_FAILURE',

  FETCH_BLOG_BY_ID_REQUEST = 'FETCH_BLOG_BY_ID_REQUEST',
  FETCH_BLOG_BY_ID_SUCCESS = 'FETCH_BLOG_BY_ID_SUCCESS',

  CREATE_BLOG = 'CREATE_BLOG',
  CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE',
  UPDATE_BLOG = 'UPDATE_BLOG',
  UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE',
}